package org.gov.model;

public enum IdentificadorAquiferoPonto {
	ACU_POROSO_NAO_DEFINIDA("Açu : Poroso : Não definida", 1),
	ACU_POROSO_REGIONAL("Açu : Poroso : Regional", 2),
	ACUNGUI_FISSURAL_NAO_DEFINIDA("Acungui : Fissural : Não definida", 3),
	ALGODOES_POROSO_NAO_DEFINIDA("Algodoes : Poroso : Não definida", 4),
	ALIANCA_POROSO_NAO_DEFINIDA("Aliança : Poroso : Não definida", 5),
	ALTER_DO_CHAO_POROSO_LOCAL("Alter do chão : Poroso : Local", 6),
	ALUVIONAR_POROSO_NAO_DEFINIDA("Aluvionar : Poroso : Não definida", 7),
	ALUVIONAR_POROSO_LOCAL("Aluvionar : Poroso : Local", 8),
	ALUVIONAR_POROSO_REGIONAL("Aluvionar : Poroso : Regional", 9),
	ALUVIONAR_POROSO_REGIONAL_LIMITADA("Aluvionar : Poroso : Regional limitada", 10),
	ANDRELANDIA_FISSURAL_NAO_DEFINIDA("Andrelandia : Fissural : Não definida", 11),
	AQUIDAUANA_POROSO_NAO_DEFINIDA("Aquidauana : Poroso : Não definida", 12),
	AQUIDAUANA_POROSO_LOCAL("Aquidauana : Poroso : Local", 13),
	AQUIDAUANA_POROSO_REGIONAL_LIMITADA("Aquidauana : Poroso : Regional limitada", 14),
	ARAXA_FISSURAL_NAO_DEFINIDA("Araxá : Fissural : Não definida", 15),
	ARAXA_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Araxá : Fissural : Restrito a zona fraturada", 16),
	BAMBUI_CARSTICO_NAO_DEFINIDA("Bambuí : Cárstico : Não definida", 17),
	BAMBUI_FISSURAL_NAO_DEFINIDA("Bambuí : Fissural : Não definida", 18),
	BAMBUI_POROSO_REGIONAL("Bambuí : Poroso : Regional", 19),
	BARBACENA_FISSURAL_NAO_DEFINIDA("Barbacena : Fissural : Não definida", 20),
	BARBACENA_POROSO_NAO_DEFINIDA("Barbacena : Poroso : Não definida", 21),
	BARREIRAS_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Barreiras : Fissural : Restrito a zona fraturada", 22),
	BARREIRAS_POROSO_NAO_DEFINIDA("Barreiras : Poroso : Não definida", 23),
	BARREIRAS_POROSO_RESTRITO_A_ZONA_FRATURADA("Barreiras : Poroso : Restrito a zona fraturada", 24),
	BAURU_POROSO_NAO_DEFINIDA("Bauru : Poroso : Não definida", 25),
	BAURU_POROSO_LOCAL("Bauru : Poroso : Local", 26),
	BAURU_POROSO_REGIONAL("Bauru : Poroso : Regional", 27),
	BAURU_POROSO_REGIONAL_LIMITADA("Bauru : Poroso : Regional limitada", 28),
	BEBEDOURO_FISSURAL_NAO_DEFINIDA("Bebedouro : Fissural : Não definida", 29),
	BEBERIBE_POROSO_NAO_DEFINIDA("Beberibe : Poroso : Não definida", 30),
	BEBERIBE_POROSO_REGIONAL("Beberibe : Poroso : Regional", 31),
	BENEFICIENTE_POROSO_REGIONAL("Beneficiente : Poroso : Regional", 32),
	BOA_VISTA_POROSO_REGIONAL("Boa vista : Poroso : Regional", 33),
	BOTUCATU_FISSURAL_NAO_DEFINIDA("Botucatu : Fissural : Não definida", 34),
	BOTUCATU_POROSO_NAO_DEFINIDA("Botucatu : Poroso : Não definida", 35),
	BOTUCATU_POROSO_LOCAL("Botucatu : Poroso : Local", 36),
	BOTUCATU_POROSO_REGIONAL("Botucatu : Poroso : Regional", 37),
	BOTUCATU_POROSO_REGIONAL_LIMITADA("Botucatu : Poroso : Regional limitada", 38),
	BOTUCATU_POROSO_RESTRITO_A_ZONA_FRATURADA("Botucatu : Poroso : Restrito a zona fraturada", 39),
	BREJO_SANTO_POROSO_NAO_DEFINIDA("Brejo santo : Poroso : Não definida", 40),
	BROTAS_POROSO_NAO_DEFINIDA("Brotas : Poroso : Não definida", 41),
	CAATINGA_CARSTICO_NAO_DEFINIDA("Caatinga : Cárstico : Não definida", 42),
	CABOCLO_FISSURAL_NAO_DEFINIDA("Caboclo : Fissural : Não definida", 43),
	CACAPAVA_POROSO_NAO_DEFINIDA("Caçapava : Poroso : Não definida", 44),
	CACAPAVA_POROSO_REGIONAL("Caçapava : Poroso : Regional", 45),
	CAIUA_POROSO_REGIONAL("Caiua : Poroso : Regional", 46),
	CAIUA_POROSO_REGIONAL_LIMITADA("Caiua : Poroso : Regional limitada", 47),
	CAMBAI_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Cambai : Fissural : Restrito a zona fraturada", 48),
	CANANEIA_POROSO_REGIONAL("Cananeia : Poroso : Regional", 49),
	CANDEIAS_POROSO_NAO_DEFINIDA("Candeias : Poroso : Não definida", 50),
	CANUDOS_FISSURAL_NAO_DEFINIDA("Canudos : Fissural : Não definida", 51),
	CAPELINHA_FISSURAL_NAO_DEFINIDA("Capelinha : Fissural : Não definida", 52),
	CAPIM_GROSSO_POROSO_NAO_DEFINIDA("Capim grosso : Poroso : Não definida", 53),
	CARACA_FISSURAL_NAO_DEFINIDA("Caraça : Fissural : Não definida", 54),
	CARAIBA_FISSURAL_NAO_DEFINIDA("Caraiba : Fissural : Não definida", 55),
	CARIRI_POROSO_NAO_DEFINIDA("Cariri : Poroso : Não definida", 56),
	CAUABURI_POROSO_REGIONAL("Cauaburi : Poroso : Regional", 57),
	CAUE_FISSURAL_NAO_DEFINIDA("Caue : Fissural : Não definida", 58),
	CHAPADA_DIAMANTINA_FISSURAL_NAO_DEFINIDA("Chapada diamantina : Fissural : Não definida", 59),
	CHAPADA_DIAMANTINA_POROSO_NAO_DEFINIDA("Chapada diamantina : Poroso : Não definida", 60),
	COBERTURA_CENOZOICA_POROSO_NAO_DEFINIDA("Cobertura cenozoica : Poroso : Não definida", 61),
	COBERTURA_CENOZOICA_POROSO_LOCAL("Cobertura cenozoica : Poroso : Local", 62),
	COBERTURA_CENOZOICA_POROSO_REGIONAL("Cobertura cenozoica : Poroso : Regional", 63),
	COBERTURA_CENOZOICA_POROSO_REGIONAL_LIMITADA("Cobertura cenozoica : Poroso : Regional limitada", 64),
	CODO_POROSO_REGIONAL("Codo : Poroso : Regional", 65),
	COLOMI_FISSURAL_NAO_DEFINIDA("Colomi : Fissural : Não definida", 66),
	COLUVIONAR_POROSO_NAO_DEFINIDA("Coluvionar : Poroso : Não definida", 67),
	COLUVIONAR_POROSO_LOCAL("Coluvionar : Poroso : Local", 68),
	COLUVIONAR_POROSO_REGIONAL("Coluvionar : Poroso : Regional", 69),
	COUTO_MAGALHAES_POROSO_REGIONAL("Couto Magalhães : Poroso : Regional", 70),
	CUIABA_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Cuiabá : Fissural : Restrito a zona fraturada", 71),
	CURUA_FISSURAL_REGIONAL("Curua : Fissural : Regional", 72),
	DIAMANTINO_POROSO_LOCAL("Diamantino : Poroso : Local", 73),
	ELUVIONAR_POROSO_NAO_DEFINIDA("Eluvionar : Poroso : Não definida", 74),
	ELUVIONAR_POROSO_LOCAL("Eluvionar : Poroso : Local", 75),
	ESPINHACO_FISSURAL_NAO_DEFINIDA("Espinhaço : Fissural : Não definida", 76),
	ESPINHACO_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Espinhaço : Fissural : Restrito a zona fraturada", 77),
	ESTRADA_NOVA_POROSO_REGIONAL("Estrada nova : Poroso : Regional", 78),
	ESTRONDO_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Estrondo : Fissural : Restrito a zona fraturada", 79),
	EXU_POROSO_NAO_DEFINIDA("Exu : Poroso : Não definida", 80),
	FACEIRA_POROSO_NAO_DEFINIDA("Faceira : Poroso : Não definida", 81),
	FURNAS_POROSO_REGIONAL("Furnas : Poroso : Regional", 82),
	FURNAS_POROSO_REGIONAL_LIMITADA("Furnas : Poroso : Regional limitada", 83),
	GRAO_PARA_FISSURAL_REGIONAL("Grão-Pará : Fissural : Regional", 84),
	GUATA_POROSO_REGIONAL("Guata : Poroso : Regional", 85),
	GUIANENSE_FISSURAL_REGIONAL("Guianense : Fissural : Regional", 86),
	ILHAS_POROSO_NAO_DEFINIDA("Ilhas : Poroso : Não definida", 87),
	INAJA_POROSO_NAO_DEFINIDA("Inaja : Poroso : Não definida", 88),
	IRAJAI_FISSURAL_NAO_DEFINIDA("Irajai : Fissural : Não definida", 89),
	IRATI_POROSO_REGIONAL("Irati : Poroso : Regional", 90),
	ITABIRA_FISSURAL_NAO_DEFINIDA("Itabira : Fissural : Não definida", 91),
	ITAITUBA_POROSO_LOCAL("Itaituba : Poroso : Local", 92),
	ITAPARICA_POROSO_NAO_DEFINIDA("Itaparica : Poroso : Não definida", 93),
	ITAPECURU_POROSO_LOCAL("Itapecuru : Poroso : Local", 94),
	ITAPECURU_POROSO_REGIONAL("Itapecuru : Poroso : Regional", 95),
	ITARARE_POROSO_NAO_DEFINIDA("Itararé : Poroso : Não definida", 96),
	ITARARE_POROSO_LOCAL("Itararé : Poroso : Local", 97),
	ITARARE_POROSO_REGIONAL("Itararé : Poroso : Regional", 98),
	JACIPARANA_POROSO_REGIONAL_LIMITADA("Jaciparana : Poroso : Regional limitada", 99),
	JACIPARANA_POROSO_RESTRITO_A_ZONA_FRATURADA("Jaciparana : Poroso : Restrito a zona fraturada", 100),
	JACOBINA_FISSURAL_NAO_DEFINIDA("Jacobina : Fissural : Não definida", 101),
	JAIBARAS_FISSURAL_NAO_DEFINIDA("Jaibaras : Fissural : Não definida", 102),
	JANDAIRA_CARSTICO_NAO_DEFINIDA("Jandaira : Cárstico : Não definida", 103),
	JANDAIRA_CARSTICO_REGIONAL("Jandaira : Cárstico : Regional", 104),
	JUA_FISSURAL_NAO_DEFINIDA("Jua : Fissural : Não definida", 105),
	JUIZ_DE_FORA_FISSURAL_NAO_DEFINIDA("Juiz de fora : Fissural : Não definida", 106),
	MACAUBAS_FISSURAL_NAO_DEFINIDA("Macaubas : Fissural : Não definida", 107),
	MACAUBAS_POROSO_NAO_DEFINIDA("Macaubas : Poroso : Não definida", 108),
	MACURURE_FISSURAL_NAO_DEFINIDA("Macurure : Fissural : Não definida", 109),
	MAECURU_POROSO_REGIONAL("Maecuru : Poroso : Regional", 110),
	MANTIQUEIRA_FISSURAL_NAO_DEFINIDA("Mantiqueira : Fissural : Não definida", 111),
	MARIZAL_POROSO_NAO_DEFINIDA("Marizal : Poroso : Não definida", 112),
	MASSACARA_POROSO_NAO_DEFINIDA("Massacara : Poroso : Não definida", 113),
	MATA_DA_CORDA_FISSURAL_NAO_DEFINIDA("Mata da corda : Fissural : Não definida", 114),
	MATA_DA_CORDA_POROSO_NAO_DEFINIDA("Mata da corda : Poroso : Não definida", 115),
	MAURITI_POROSO_NAO_DEFINIDA("Mauriti : Poroso : Não definida", 116),
	MIABA_CARSTICO_NAO_DEFINIDA("Miaba : Cárstico : Não definida", 117),
	MINAS_FISSURAL_NAO_DEFINIDA("Minas : Fissural : Não definida", 118),
	MISSAO_VELHA_POROSO_NAO_DEFINIDA("Missão velha : Poroso : Não definida", 119),
	MONTE_ALEGRE_POROSO_LOCAL("Monte alegre : Poroso : Local", 120),
	MORRO_DO_CHAPEU_FISSURAL_NAO_DEFINIDA("Morro do chapéu : Fissural : Não definida", 121),
	NOVA_LIMA_FISSURAL_NAO_DEFINIDA("Nova lima : Fissural : Não definida", 122),
	OLHOS_D_AGUA_CARSTICO_NAO_DEFINIDA("Olhos d'agua : Cárstico : Não definida", 123),
	OURICURI_DO_OURO_FISSURAL_NAO_DEFINIDA("Ouricuri do ouro : Fissural : Não definida", 124),
	PALERMO_POROSO_REGIONAL("Palermo : Poroso : Regional", 125),
	PARAGUACU_FISSURAL_NAO_DEFINIDA("Paraguaçu : Fissural : Não definida", 126),
	PARAIBA_DO_SUL_FISSURAL_NAO_DEFINIDA("Paraíba do sul : Fissural : Não definida", 127),
	PARANOA_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Paranoá : Fissural : Restrito a zona fraturada", 128),
	PARAOPEBA_FISSURAL_NAO_DEFINIDA("Paraopeba : Fissural : Não definida", 129),
	PARAOPEBA_CARSTICO_NAO_DEFINIDA("Paraopeba : Cárstico : Não definida", 130),
	PARECIS_POROSO_REGIONAL("Parecis : Poroso : Regional", 131),
	PARECIS_POROSO_REGIONAL_LIMITADA("Parecis : Poroso : Regional limitada", 132),
	PASSA_DOIS_POROSO_NAO_DEFINIDA("Passa dois : Poroso : Não definida", 133),
	PASSA_DOIS_POROSO_LOCAL("Passa dois : Poroso : Local", 134),
	PASSA_DOIS_POROSO_REGIONAL("Passa dois : Poroso : Regional", 135),
	PASSA_DOIS_POROSO_REGIONAL_LIMITADA("Passa dois : Poroso : Regional limitada", 136),
	PIAUI_FISSURAL_REGIONAL("Piauí : Fissural : Regional", 137),
	PIMENTA_BUENO_FISSURAL_NAO_DEFINIDA("Pimenta Bueno : Fissural : Não definida", 138),
	PIMENTA_BUENO_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Pimenta Bueno : Fissural : Restrito a zona fraturada", 139),
	PIRABAS_POROSO_LOCAL("Pirabas : Poroso : Local", 140),
	PIRACICABA_FISSURAL_NAO_DEFINIDA("Piracicaba : Fissural : Não definida", 141),
	PONTA_GROSSA_POROSO_LOCAL("Ponta grossa : Poroso : Local", 142),
	PONTA_GROSSA_POROSO_REGIONAL_LIMITADA("Ponta grossa : Poroso : Regional limitada", 143),
	PORONGOS_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Porongos : Fissural : Restrito a zona fraturada", 144),
	RIO_BONITO_POROSO_NAO_DEFINIDA("Rio bonito : Poroso : Não definida", 145),
	RIO_BONITO_POROSO_REGIONAL("Rio bonito : Poroso : Regional", 146),
	RIO_DA_BATATEIRA_POROSO_NAO_DEFINIDA("Rio da batateira : Poroso : Não definida", 147),
	RIO_DAS_VELHAS_FISSURAL_NAO_DEFINIDA("Rio das velhas : Fissural : Não definida", 148),
	RIO_DO_RASTRO_POROSO_REGIONAL("Rio do rastro : Poroso : Regional", 149),
	RIO_DO_SUL_POROSO_REGIONAL("Rio do sul : Poroso : Regional", 150),
	RIO_DOS_REMEDIOS_FISSURAL_NAO_DEFINIDA("Rio dos remédios : Fissural : Não definida", 151),
	RIO_GUAMA_POROSO_LOCAL("Rio Guamá : Poroso : Local", 152),
	RIO_PARDO_CARSTICO_NAO_DEFINIDA("Rio pardo : Cárstico : Não definida", 153),
	RIO_PRETO_FISSURAL_NAO_DEFINIDA("Rio preto : Fissural : Não definida", 154),
	ROCHA_CRISTALINA_CARSTICO_NAO_DEFINIDA("Rocha cristalina : Cárstico : Não definida", 155),
	ROCHA_CRISTALINA_FISSURAL_NAO_DEFINIDA("Rocha cristalina : Fissural : Não definida", 156),
	ROCHA_CRISTALINA_FISSURAL_LOCAL("Rocha cristalina : Fissural : Local", 157),
	ROCHA_CRISTALINA_FISSURAL_REGIONAL("Rocha cristalina : Fissural : Regional", 158),
	ROCHA_CRISTALINA_FISSURAL_REGIONAL_LIMITADA("Rocha cristalina : Fissural : Regional limitada", 159),
	ROCHA_CRISTALINA_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Rocha cristalina : Fissural : Restrito a zona fraturada", 160),
	ROCHA_SEDIMENTAR_CARSTICO_NAO_DEFINIDA("Rocha sedimentar : Cárstico : Não definida", 161),
	ROCHA_SEDIMENTAR_FISSURAL_NAO_DEFINIDA("Rocha sedimentar : Fissural : Não definida", 162),
	ROCHA_SEDIMENTAR_POROSO_NAO_DEFINIDA("Rocha sedimentar : Poroso : Não definida", 163),
	ROCHA_SEDIMENTAR_POROSO_LOCAL("Rocha sedimentar : Poroso : Local", 164),
	ROCHA_SEDIMENTAR_POROSO_REGIONAL("Rocha sedimentar : Poroso : Regional", 165),
	ROCHA_SEDIMENTAR_POROSO_REGIONAL_LIMITADA("Rocha sedimentar : Poroso : Regional limitada", 166),
	ROCHA_SEDIMENTAR_POROSO_RESTRITO_A_ZONA_FRATURADA("Rocha sedimentar : Poroso : Restrito a zona fraturada", 167),
	ROSARIO_DO_SUL_POROSO_REGIONAL_LIMITADA("Rosário do sul : Poroso : Regional limitada", 168),
	SALITRE_CARSTICO_NAO_DEFINIDA("Salitre : Cárstico : Não definida", 169),
	SALVADOR_POROSO_NAO_DEFINIDA("Salvador : Poroso : Não definida", 170),
	SANTA_CRUZ_FISSURAL_NAO_DEFINIDA("Santa cruz : Fissural : Não definida", 171),
	SANTA_HELENA_FISSURAL_NAO_DEFINIDA("Santa helena : Fissural : Não definida", 172),
	SANTANA_FISSURAL_NAO_DEFINIDA("Santana : Fissural : Não definida", 173),
	SANTO_ONOFRE_FISSURAL_NAO_DEFINIDA("Santo Onofre : Fissural : Não definida", 174),
	SAO_PAULO_POROSO_LOCAL("São Paulo : Poroso : Local", 175),
	SAO_PAULO_POROSO_REGIONAL("São Paulo : Poroso : Regional", 176),
	SAO_PAULO_POROSO_REGIONAL_LIMITADA("São Paulo : Poroso : Regional limitada", 177),
	SAO_SEBASTIAO_POROSO_NAO_DEFINIDA("São Sebastião : Poroso : Não definida", 178),
	SAO_SEBASTIAO_POROSO_REGIONAL_LIMITADA("São Sebastião : Poroso : Regional limitada", 179),
	SEDIMENTO_COSTEIRO_POROSO_REGIONAL("Sedimento costeiro : Poroso : Regional", 180),
	SEDIMENTO_COSTEIRO_POROSO_REGIONAL_LIMITADA("Sedimento costeiro : Poroso : Regional limitada", 181),
	SEDIMENTO_INCONSOLIDADO_POROSO_NAO_DEFINIDA("Sedimento inconsolidado : Poroso : Não definida", 182),
	SERGI_POROSO_NAO_DEFINIDA("Sergi : Poroso : Não definida", 183),
	SERIDO_FISSURAL_NAO_DEFINIDA("Seridó : Fissural : Não definida", 184),
	SERRA_DA_BOA_ESPERANCA_FISSURAL_NAO_DEFINIDA("Serra da boa esperança : Fissural : Não definida", 185),
	SERRA_DO_PARAISO_CARSTICO_NAO_DEFINIDA("Serra do paraíso : Cárstico : Não definida", 186),
	SERRA_GERAL_FISSURAL_NAO_DEFINIDA("Serra geral : Fissural : Não definida", 187),
	SERRA_GERAL_FISSURAL_LOCAL("Serra geral : Fissural : Local", 188),
	SERRA_GERAL_FISSURAL_REGIONAL("Serra geral : Fissural : Regional", 189),
	SERRA_GERAL_FISSURAL_REGIONAL_LIMITADA("Serra geral : Fissural : Regional limitada", 190),
	SERRA_GERAL_FISSURAL_RESTRITO_A_ZONA_FRATURADA("Serra geral : Fissural : Restrito a zona fraturada", 191),
	SERRA_GERAL_POROSO_RESTRITO_A_ZONA_FRATURADA("Serra geral : Poroso : Restrito a zona fraturada", 192),
	SERRA_GRANDE_POROSO_NAO_DEFINIDA("Serra grande : Poroso : Não definida", 193),
	SERRA_GRANDE_POROSO_RESTRITO_A_ZONA_FRATURADA("Serra grande : Poroso : Restrito a zona fraturada", 194),
	SERTANIA_FISSURAL_NAO_DEFINIDA("Sertania : Fissural : Não definida", 195),
	SETE_LAGOAS_CARSTICO_NAO_DEFINIDA("Sete lagoas : Cárstico : Não definida", 196),
	SETE_LAGOAS_CARSTICO_REGIONAL_LIMITADA("Sete lagoas : Cárstico : Regional limitada", 197),
	SOLIMOES_POROSO_REGIONAL("Solimoes : Poroso : Regional", 198),
	SOLIMOES_POROSO_REGIONAL_LIMITADA("Solimoes : Poroso : Regional limitada", 199),
	SOUZA_POROSO_NAO_DEFINIDA("Souza : Poroso : Não definida", 200),
	TACARATU_POROSO_NAO_DEFINIDA("Tacaratu : Poroso : Não definida", 201),
	TACARATU_POROSO_REGIONAL("Tacaratu : Poroso : Regional", 202),
	TAUBATE_POROSO_NAO_DEFINIDA("Taubate : Poroso : Não definida", 203),
	TAUBATE_POROSO_REGIONAL("Taubate : Poroso : Regional", 204),
	TAUBATE_POROSO_REGIONAL_LIMITADA("Taubate : Poroso : Regional limitada", 205),
	TOMBADOR_FISSURAL_NAO_DEFINIDA("Tombador : Fissural : Não definida", 206),
	TREMEMBE_POROSO_NAO_DEFINIDA("Tremembe : Poroso : Não definida", 207),
	TRES_MARIAS_FISSURAL_NAO_DEFINIDA("Tres marias : Fissural : Não definida", 208),
	TRES_MARIAS_POROSO_NAO_DEFINIDA("Tres marias : Poroso : Não definida", 209),
	TUBARAO_POROSO_NAO_DEFINIDA("Tubarao : Poroso : Não definida", 210),
	TUBARAO_POROSO_LOCAL("Tubarao : Poroso : Local", 211),
	TUBARAO_POROSO_REGIONAL("Tubarao : Poroso : Regional", 212),
	TUBARAO_POROSO_REGIONAL_LIMITADA("Tubarao : Poroso : Regional limitada", 213),
	TUPANCIRETA_POROSO_REGIONAL_LIMITADA("Tupancireta : Poroso : Regional limitada", 214),
	UBAJARA_POROSO_NAO_DEFINIDA("Ubajara : Poroso : Não definida", 215),
	URUCUIA_POROSO_NAO_DEFINIDA("Urucuia : Poroso : Não definida", 216),
	URUCUIA_POROSO_REGIONAL("Urucuia : Poroso : Regional", 217),
	VARGINHA_GUAXUPE_FISSURAL_NAO_DEFINIDA("Varginha-guaxupe : Fissural : Não definida", 218),
	XINGU_FISSURAL_REGIONAL_LIMITADA("Xingu : Fissural : Regional limitada", 219),
	XINGU_POROSO_REGIONAL("Xingu : Poroso : Regional", 220),
	XINGU_POROSO_REGIONAL_LIMITADA("Xingu : Poroso : Regional limitada", 221),
	CABECAS_POROSO_NAO_DEFINIDA("Cabeças : Poroso : Não definida", 222),
	CASA_NOVA_POROSO_NAO_DEFINIDA("Casa nova : Poroso : Não definida", 223),
	CORDA_POROSO_NAO_DEFINIDA("Corda : Poroso : Não definida", 224),
	FEIRA_NOVA_POROSO_NAO_DEFINIDA("Feira nova : Poroso : Não definida", 225),
	GRAJAU_POROSO_NAO_DEFINIDA("Grajau : Poroso : Não definida", 226),
	LONGA_POROSO_NAO_DEFINIDA("Longa : Poroso : Não definida", 227),
	MOSQUITO_POROSO_NAO_DEFINIDA("Mosquito : Poroso : Não definida", 228),
	MOTUCA_POROSO_NAO_DEFINIDA("Motuca : Poroso : Não definida", 229),
	NAO_DEFINIDO_POROSO_NAO_DEFINIDA("Não definido : Poroso : Não definida", 230),
	PASTOS_BONS_POROSO_NAO_DEFINIDA("Pastos bons : Poroso : Não definida", 231),
	PEDRA_DE_FOGO_POROSO_NAO_DEFINIDA("Pedra de fogo : Poroso : Não definida", 232),
	PIMENTEIRAS_POROSO_NAO_DEFINIDA("Pimenteiras : Poroso : Não definida", 233),
	SAMBAIBA_POROSO_NAO_DEFINIDA("Sambaiba : Poroso : Não definida", 234),
	SANTO_AMARO_POROSO_NAO_DEFINIDA("Santo amaro : Poroso : Não definida", 235),
	SAO_JULIAO_FISSURAL_NAO_DEFINIDA("Sao juliao : Fissural : Não definida", 236),
	SARAIVA_POROSO_NAO_DEFINIDA("Saraiva : Poroso : Não definida", 237),
	SARDINHA_FISSURAL_NAO_DEFINIDA("Sardinha : Fissural : Não definida", 238),
	NAO_DEFINIDO_CARSTICO_NAO_DEFINIDA("Não definido : Cárstico : Não definida", 239),
	NAO_DEFINIDO_FISSURAL_NAO_DEFINIDA("Não definido : Fissural : Não definida", 240),
	NAO_DEFINIDO_NAO_DEFINIDO_NAO_DEFINIDA("Não definido : Não definido : Não definida", 241),
	BOA_VIAGEM_POROSO_LOCAL("Boa Viagem : Poroso : Local", 242);


    private int chave;
    private String valor;

    IdentificadorAquiferoPonto(String valor, int chave) {
        this.valor = valor;
        this.chave = chave;
    }

	public int getChave() {
		return chave;
	}

	public void setChave(int chave) {
		this.chave = chave;
	}

	public String getValor() {
		return valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
