package org.gov.model;

public enum Sir_tct_cd {
	BROCOLIS("Brócolis"),
	COUVE_DE_BRUXELAS("Couve de bruxelas"),
	REPOLHO("Repolho"),
	CENOURA("Cenoura"),
	COUVE_FLOR("Couve flor"),
	AIPO("Aipo"),
	ALHO("Alho"),
	ALFACE("Alface"),
	CEBOLAS_SECAS("Cebolas (secas)"),
	CEBOLAS_VERDES("Cebolas (verdes)"),
	CEBOLAS_SEMENTES("Cebolas (sementes)"),
	ESPINAFRE("Espinafre"),
	RABANETE("Rabanete"),
	BERINGELA("Beringela"),
	PIMENTAO("Pimentão"),
	TOMATE("Tomate"),
	MELAO_CANTALOUPE("Melão cantaloupe"),
	PEPINO_COLHEITA_FRESCA("Pepino (colheita fresca)"),
	PEPINO_COLHEITA_MECANICA("Pepino (colheita mecânica)"),
	ABOBORA("Abóbora"),
	ABOBRINHA("Abobrinha"),
	MELOES("Melões"),
	MELANCIAS("Melancias"),
	BETERRABAS("Beterrabas"),
	MANDIOCAS_ANO_1("Mandiocas  (ano 1)"),
	MANDIOCAS_ANO_2("Mandiocas  (ano 2)"),
	PASTINACA_CHIRIVIA("Pastinaca (chirívia)"),
	BATATA("Batata"),
	BATATA_DOCE("Batata doce"),
	NABO_E_NABO_REDONDO("Nabo (e nabo-redondo)"),
	BETERRABA_ACUCAREIRA("Beterraba açucareira"),
	FEIJAO_VERDE("Feijão verde"),
	FEIJOES_GRAOS("Feijões (grãos)"),
	GRAO_DE_BICO("Grão de bico"),
	FAVA_COLHEITA_FRESCA("Fava (colheita fresca)"),
	FAVA_GRAO_SEMENTE("Fava (grão, semente)"),
	FEIJAO_CAUPI_E_FEIJAO_MUNGO("Feijão caupi (e feijão mungo)"),
	AMENDOIM("Amendoim"),
	LENTILHA("Lentilha"),
	ERVILHA_FRESCA("Ervilha (fresca)"),
	ERVILHA_SECA_SEMENTE("Ervilha (seca, semente)"),
	SOJA("Soja"),
	ALCACHOFRAS("Alcachofras"),
	ASPARGOS("Aspargos"),
	HORTELA("Hortelã"),
	MORANGOS("Morangos"),
	ALGODAO("Algodão"),
	LINHO("Linho"),
	SISAL("Sisal"),
	MAMONA("Mamona"),
	COLZA_CANOLA("Colza, Canola"),
	CARTAMO("Cártamo"),
	GEGELIM("Gegelim"),
	GIRASSOL("Girassol"),
	CEVADA("Cevada"),
	AVEIA("Aveia"),
	TRIGO_PRIMAVERA("Trigo primavera"),
	TRIGO_INVERNO("Trigo inverno"),
	MILHO_GRAO_E_PIPOCA("Milho (grão e pipoca)"),
	MILHO_DOCE("Milho (doce)"),
	MILHETO("Milheto"),
	SORGO_GRAO("Sorgo (grão)"),
	SORGO_DOCE("Sorgo (doce)"),
	ARROZ("Arroz"),
	ALFAFA_FENO_VARIOS_CORTES_FEITOS_MEDIOS("Alfafa (feno, vários cortes, feitos médios)"),
	ALFAFA_FENO_CICLO_INDIVIDUAL_DE_CORTE("Alfafa (feno, ciclo individual de corte)"),
	ALFAFA_PARA_SEMENTE("Alfafa (para semente)"),
	CAPIM_BERMUDA_FENO_VARIOS_CORTES_EFEITOS_MEDIOS("Capim Bermuda (feno, vários cortes, efeitos médios)"),
	CAPIM_BERMUDA_COLHEITA_DE_PRIMAVERA_PARA_SEMENTE("Capim Bermuda (colheita de primavera para semente)"),
	TREVO_FENO_VARIOS_CORTES_EFEITOS_MEDIOS("Trevo (feno, vários cortes, efeitos médios)"),
	TREVO_FENO_CICLO_INDIVIDUAL_DE_CORTE("Trevo (feno, ciclo individual de corte)"),
	CAPIM_CENTEIO_FENO_VARIOS_CORTES_EFEITOS_MEDIOS("Capim centeio (feno, vários cortes, efeitos médios)"),
	CAPIM_SUDAO_E_ANUAL_FENO_VARIOS_CORTES_EFEITOS_MEDIOS("Capim Sudão ¿ anual (feno, vários cortes, efeitos médios)"),
	CAPIM_SUDAO_E_ANUAL_FENO_CICLO_INDIVIDUAL_DE_CORTE("Capim Sudão ¿ anual (feno, ciclo individual de corte)"),
	PASTAGEM_PASTOREIO_ROTATIVO("Pastagem (pastoreio rotativo)"),
	PASTAGEM_PASTOREIO_EXTENSIVO("Pastagem (pastoreio extensivo)"),
	GRAMADOS_ESTACAO_FRIA("Gramados (estação fria)"),
	GRAMADOS_ESTACAO_QUENTE("Gramados (estação quente)"),
	BANANA_1_ANO("Banana (1º ano)"),
	BANANA_2_ANO("Banana (2º ano)"),
	CACAU("Cacau"),
	CAFE_POUCA_COBERTURA_DE_CHAO("Café (pouca cobertura de chão)"),
	CAFE_COM_ERVAS("Café (com ervas)"),
	TAMAREIRA_TAMARAS("Tamareira (Tâmaras)"),
	PALMEIRA("Palmeira"),
	ABACAXI_SOLO_LIMPO("Abacaxi (solo limpo)"),
	ABACAXI_COM_COBERTURA_DE_GRAMINEAS("Abacaxi (com cobertura de gramíneas)"),
	SERINGUEIRA("Seringueira"),
	CHA_SEM_SOMBREAMENTO("Chá (sem sombreamento)"),
	CHA_COM_ARVORES_DE_SOMBREAMENTO("Chá (com árvores de sombreamento)"),
	AMORA_MIRTILO_ARBUSTOS("Amora, mirtilo (arbustos)"),
	UVAS_MESA_OU_PASSAS("Uvas (mesa ou passas)"),
	UVAS_VINHO("Uvas (vinho)"),
	LUPULO("Lúpulo"),
	AMENDOAS_SEM_COBERTURA_DE_CHAO("Amêndoas (sem cobertura de chão)"),
	MACAS_CEREJAS_E_PERAS_SEM_COBERTURA_DE_CHAO_COM_GEADAS("Maças, cerejas e peras (sem cobertura de chão, com geadas)"),
	MACAS_CEREJAS_E_PERAS_SEM_COBERTURA_DE_CHAO_SEM_GEADAS("Maças, cerejas e peras (sem cobertura de chão, sem geadas)"),
	MACAS_CEREJAS_E_PERAS_COBERTURA_DE_CHAO_ATIVA_COM_GEADAS("Maças, cerejas e peras (cobertura de chão ativa, com geadas)"),
	MACAS_CEREJAS_E_PERAS_COBERTURA_DE_CHAO_ATIVA_SEM_GEADAS("Maças, cerejas e peras (cobertura de chão ativa, sem geadas)"),
	DAMASCOS_PESSEGOS_SEM_COBERTURA_DE_CHAO_COM_GEADAS("Damascos, pêssegos (sem cobertura de chão, com geadas)"),
	DAMASCOS_PESSEGOS_SEM_COBERTURA_DE_CHAO_SEM_GEADAS("Damascos, pêssegos (sem cobertura de chão, sem geadas)"),
	DAMASCOS_PESSEGOS_COBERTURA_DE_CHAO_ATIVA_COM_GEADAS("Damascos, pêssegos (cobertura de chão ativa, com geadas)"),
	DAMASCOS_PESSEGOS_COBERTURA_DE_CHAO_ATIVA_SEM_GEADAS("Damascos, pêssegos (cobertura de chão ativa, sem geadas)"),
	ABACATE_SEM_COBERTURA_DE_CHAO("Abacate, sem cobertura de chão"),
	CITRUS_SEM_COBERTURA_DE_CHAO_70PCT_DE_DOSSEL("Citrus, sem cobertura de chão (70% de dossel)"),
	CITRUS_SEM_COBERTURA_DE_CHAO_50PCT_DE_DOSSEL("Citrus, sem cobertura de chão (50% de dossel)"),
	CITRUS_SEM_COBERTURA_DE_CHAO_20PCT_DE_DOSSEL("Citrus, sem cobertura de chão (20% de dossel)"),
	CITRUS_COBERTURA_DE_CHAO_ATIVA_OU_INVASORAS_70PCT_DE_DOSSEL("Citrus, cobertura de chão ativa ou invasoras (70% de dossel)"),
	CITRUS_COBERTURA_DE_CHAO_ATIVA_OU_INVASORAS_50PCT_DE_DOSSEL("Citrus, cobertura de chão ativa ou invasoras (50% de dossel)"),
	CITRUS_COBERTURA_DE_CHAO_ATIVA_OU_INVASORAS_20PCT_DE_DOSSEL("Citrus, cobertura de chão ativa ou invasoras (20% de dossel)"),
	KIWI("Kiwi"),
	OLIVEIRA_40_A_60PCT_DE_COBERTURA_DO_SOLO_PELO_DOSSEL("Oliveira (40 a 60% de cobertura do solo pelo dossel)"),
	PISTACHE_SEM_COBERTURA_DO_SOLO("Pistache, sem cobertura do solo"),
	NOGUEIRA_POMARES("Nogueira (pomares)"),
	CONIFERAS("Coníferas"),
	BANHADOS_COM_TABOAS_JUNCOS__COM_GEADAS("Banhados com taboas, juncos,  com geadas"),
	BANHADOS_COM_TABOAS_JUNCOS__SEM_GEADAS("Banhados com taboas, juncos,  sem geadas"),
	BANHADOS_VEGETACAO_BAIXA_SEM_GEADAS("Banhados, vegetação baixa, sem geadas"),
	PANTANO_BANHADOS__AGUA_ESTAGNADA("Pântano, banhados,  água estagnada"),
	PANTANO_BANHADO_SOLO_UMIDO("Pântano, banhado, solo úmido"),
	CANA_DE_ACUCAR("Cana-de-açúcar"),
	TRIGO("Trigo"),
	ABIU("Abiu"),
	ACAI("Açaí"),
	ACEROLA("Acerola"),
	AMEIXA("Ameixa"),
	ARACA("Araça"),
	ATEMOIA("Atemoia"),
	BURITI("Buriti"),
	BURITIBA("Buritiba"),
	CAJU("Caju"),
	CAQUI("Caqui"),
	CARAMBOLA("Carambola"),
	CAJA("Caja"),
	CAJAMANGA("Cajamanga"),
	COCO_VERDE("Coco Verde"),
	CUPUACU("Cupuaçu"),
	FIGO("Figo"),
	GOIABA("Goiaba"),
	GRAVIOLA("Graviola"),
	JABOTICABA("Jaboticaba"),
	JACA("Jaca"),
	JAMBO("Jambo"),
	JENIPAPO("Jenipapo"),
	JUCARA("Juçara"),
	LICHIA("Lichia"),
	MANGABA("Mangaba"),
	MANGOSTAO("Mangostao"),
	MAMAO("Mamao"),
	MANGA("Manga"),
	MARACUJA("Maracuja"),
	MURICI("Murici"),
	NECTARINA("Nectarina"),
	NOZ_MACADAMIA("Noz Macadamia"),
	PEQUI("Pequi"),
	PESSEGO("Pessego"),
	PINHA("Pinha"),
	PITANGA("Pitanga"),
	PUPUNHA("Pupunha"),
	RAMBUTAN("Rambutan"),
	ROMA("Roma"),
	SAPOTI("Sapoti"),
	SERIGUELA("Seriguela"),
	TAMARINDO("Tamarindo"),
	TANGERINA("Tangerina"),
	UMBU("Umbu"),
	AIPIM("Aipim"),
	BATATINHA("Batatinha"),
	CANELA("Canela"),
	CHUCHU("Chuchu"),
	COENTRO("Coentro"),
	COMINHO("Cominho"),
	INHAME("Inhame"),
	QUIABO("Quiabo"),
	PIMENTA("Pimenta"),
	MAXIXE("Maxixe"),
	CARA("Cará"),
	COUVE_OU_COUVE_SIMPLES("Couve (ou Couve simples)"),
	FEIJAO_VIGNA("Feijão Vigna"),
	ALGAROBA("Algaroba"),
	FLORES("FLORES"),
	CROTALARIA_ARBUSTO("Crotalaria (Arbusto)"),
	CAJARANA("Cajarana"),
	BUCHA("Bucha"),
	VAGEM("Vagem"),
	COGUMELO("Cogumelo"),
	CEBOLINHA("Cebolinha"),
	SALSA("Salsa"),
	HORTALICAS("Hortaliças"),
	COCO_SECO("Coco Seco"),
	MILHO_VERDE("Milho-verde"),
	GILO("Giló"),
	FUMO("Fumo"),
	POMAR("Pomar"),
	EUCALIPITO("Eucalipito");

	private String descricao;

	Sir_tct_cd(String desc) {
		this.descricao = desc;
	}

	public String getDescricao() {
		return descricao.toUpperCase();
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
