package org.gov.model;

public enum TipoCultura {
	BROCOLIS("Brócolis", 1),
	COUVE_DE_BRUXELAS("Couve de bruxelas", 2),
	REPOLHO("Repolho", 3),
	CENOURA("Cenoura", 4),
	COUVE_FLOR("Couve flor", 5),
	AIPO("Aipo", 6),
	ALHO("Alho", 7),
	ALFACE("Alface", 8),
	CEBOLAS_SECAS("Cebolas (secas)", 9),
	CEBOLAS_VERDES("Cebolas (verdes)", 10),
	CEBOLAS_SEMENTES("Cebolas (sementes)", 11),
	ESPINAFRE("Espinafre", 12),
	RABANETE("Rabanete", 13),
	BERINGELA("Beringela", 14),
	PIMENTAO("Pimentão", 15),
	TOMATE("Tomate", 16),
	MELAO_CANTALOUPE("Melão cantaloupe", 17),
	PEPINO_COLHEITA_FRESCA("Pepino (colheita fresca)", 18),
	PEPINO_COLHEITA_MECANICA("Pepino (colheita mecânica)", 19),
	ABOBORA("Abóbora", 20),
	ABOBRINHA("Abobrinha", 21),
	MELOES("Melões", 22),
	MELANCIAS("Melancias", 23),
	BETERRABAS("Beterrabas", 24),
	MANDIOCAS_ANO_1("Mandiocas (ano 1)", 25),
	MANDIOCAS_ANO_2("Mandiocas (ano 2)", 26),
	PASTINACA_CHIRIVIA("Pastinaca (chirívia)", 27),
	BATATA("Batata", 28),
	BATATA_DOCE("Batata doce", 29),
	NABO_E_NABO_REDONDO("Nabo (e nabo-redondo)", 30),
	BETERRABA_ACUCAREIRA("Beterraba açucareira", 31),
	FEIJAO_VERDE("Feijão verde", 32),
	FEIJOES_GRAOS("Feijões (grãos)", 33),
	GRAO_DE_BICO("Grão de bico", 34),
	FAVA_COLHEITA_FRESCA("Fava (colheita fresca)", 35),
	FAVA_GRAO_SEMENTE("Fava (grão, semente)", 36),
	FEIJAO_CAUPI_E_FEIJAO_MUNGO("Feijão caupi (e feijão mungo)", 37),
	AMENDOIM("Amendoim", 38),
	LENTILHA("Lentilha", 39),
	ERVILHA_FRESCA("Ervilha (fresca)", 40),
	ERVILHA_SECA_SEMENTE("Ervilha (seca, semente)", 41),
	SOJA("Soja", 42),
	ALCACHOFRAS("Alcachofras", 43),
	ASPARGOS("Aspargos", 44),
	HORTELA("Hortelã", 45),
	MORANGOS("Morangos", 46),
	ALGODAO("Algodão", 47),
	LINHO("Linho", 48),
	SISAL("Sisal", 49),
	MAMONA("Mamona", 50),
	COLZA_CANOLA("Colza, Canola", 51),
	CARTAMO("Cártamo", 52),
	GEGELIM("Gegelim", 53),
	GIRASSOL("Girassol", 54),
	CEVADA("Cevada", 55),
	AVEIA("Aveia", 56),
	TRIGO_PRIMAVERA("Trigo primavera", 57),
	TRIGO_INVERNO("Trigo inverno", 58),
	MILHO_GRAO_E_PIPOCA("Milho (grão e pipoca)", 59),
	MILHO_DOCE("Milho (doce)", 60),
	MILHETO("Milheto", 61),
	SORGO_GRAO("Sorgo (grão)", 62),
	SORGO_DOCE("Sorgo (doce)", 63),
	ARROZ("Arroz", 64),
	ALFAFA_FENO_VARIOS_CORTES_FEITOS_MEDIOS("Alfafa (feno, vários cortes, feitos médios)", 65),
	ALFAFA_FENO_CICLO_INDIVIDUAL_DE_CORTE("Alfafa (feno, ciclo individual de corte)", 66),
	ALFAFA_PARA_SEMENTE("Alfafa (para semente)", 67),
	CAPIM_BERMUDA_FENO_VARIOS_CORTES_EFEITOS_MEDIOS("Capim Bermuda (feno, vários cortes, efeitos médios)", 68),
	CAPIM_BERMUDA_COLHEITA_DE_PRIMAVERA_PARA_SEMENTE("Capim Bermuda (colheita de primavera para semente)", 69),
	TREVO_FENO_VARIOS_CORTES_EFEITOS_MEDIOS("Trevo (feno, vários cortes, efeitos médios)", 70),
	TREVO_FENO_CICLO_INDIVIDUAL_DE_CORTE("Trevo (feno, ciclo individual de corte)", 71),
	CAPIM_CENTEIO_FENO_VARIOS_CORTES_EFEITOS_MEDIOS("Capim centeio (feno, vários cortes, efeitos médios)", 72),
	CAPIM_SUDAO_ANUAL_FENO_VARIOS_CORTES_EFEITOS_MEDIOS("Capim Sudão ¿ anual (feno, vários cortes, efeitos médios)", 73),
	CAPIM_SUDAO_ANUAL_FENO_CICLO_INDIVIDUAL_DE_CORTE("Capim Sudão ¿ anual (feno, ciclo individual de corte)", 74),
	PASTAGEM_PASTOREIO_ROTATIVO("Pastagem (pastoreio rotativo)", 75),
	PASTAGEM_PASTOREIO_EXTENSIVO("Pastagem (pastoreio extensivo)", 76),
	GRAMADOS_ESTACAO_FRIA("Gramados (estação fria)", 77),
	GRAMADOS_ESTACAO_QUENTE("Gramados (estação quente)", 78),
	BANANA_1º_ANO("Banana (1º ano)", 79),
	BANANA_2º_ANO("Banana (2º ano)", 80),
	CACAU("Cacau", 81),
	CAFE_POUCA_COBERTURA_DE_CHAO("Café (pouca cobertura de chão)", 82),
	CAFE_COM_ERVAS("Café (com ervas)", 83),
	TAMAREIRA_TAMARAS("Tamareira (Tâmaras)", 84),
	PALMEIRA("Palmeira", 85),
	ABACAXI_SOLO_LIMPO("Abacaxi (solo limpo)", 86),
	ABACAXI_COM_COBERTURA_DE_GRAMINEAS("Abacaxi (com cobertura de gramíneas)", 87),
	SERINGUEIRA("Seringueira", 88),
	CHA_SEM_SOMBREAMENTO("Chá (sem sombreamento)", 89),
	CHA_COM_ARVORES_DE_SOMBREAMENTO("Chá (com árvores de sombreamento)", 90),
	AMORA_MIRTILO_ARBUSTOS("Amora, mirtilo (arbustos)", 91),
	UVAS_MESA_OU_PASSAS("Uvas (mesa ou passas)", 92),
	UVAS_VINHO("Uvas (vinho)", 93),
	LUPULO("Lúpulo", 94),
	AMENDOAS_SEM_COBERTURA_DE_CHAO("Amêndoas (sem cobertura de chão)", 95),
	MACAS_CEREJAS_E_PERAS_SEM_COBERTURA_DE_CHAO_COM_GEADAS("Maças, cerejas e peras (sem cobertura de chão, com geadas)", 96),
	MACAS_CEREJAS_E_PERAS_SEM_COBERTURA_DE_CHAO_SEM_GEADAS("Maças, cerejas e peras (sem cobertura de chão, sem geadas)", 97),
	MACAS_CEREJAS_E_PERAS_COBERTURA_DE_CHAO_ATIVA_COM_GEADAS("Maças, cerejas e peras (cobertura de chão ativa, com geadas)", 98),
	MACAS_CEREJAS_E_PERAS_COBERTURA_DE_CHAO_ATIVA_SEM_GEADAS("Maças, cerejas e peras (cobertura de chão ativa, sem geadas)", 99),
	DAMASCOS_PESSEGOS_SEM_COBERTURA_DE_CHAO_COM_GEADAS("Damascos, pêssegos (sem cobertura de chão, com geadas)", 100),
	DAMASCOS_PESSEGOS_SEM_COBERTURA_DE_CHAO_SEM_GEADAS("Damascos, pêssegos (sem cobertura de chão, sem geadas)", 101),
	DAMASCOS_PESSEGOS_COBERTURA_DE_CHAO_ATIVA_COM_GEADAS("Damascos, pêssegos (cobertura de chão ativa, com geadas)", 102),
	DAMASCOS_PESSEGOS_COBERTURA_DE_CHAO_ATIVA_SEM_GEADAS("Damascos, pêssegos (cobertura de chão ativa, sem geadas)", 103),
	ABACATE_SEM_COBERTURA_DE_CHAO("Abacate, sem cobertura de chão", 104),
	CITRUS_SEM_COBERTURA_DE_CHAO_70_DE_DOSSEL("Citrus, sem cobertura de chão (70% de dossel)", 105),
	CITRUS_SEM_COBERTURA_DE_CHAO_50_DE_DOSSEL("Citrus, sem cobertura de chão (50% de dossel)", 106),
	CITRUS_SEM_COBERTURA_DE_CHAO_20_DE_DOSSEL("Citrus, sem cobertura de chão (20% de dossel)", 107),
	CITRUS_COBERTURA_DE_CHAO_ATIVA_OU_INVASORAS_70_DE_DOSSEL("Citrus, cobertura de chão ativa ou invasoras (70% de dossel)", 108),
	CITRUS_COBERTURA_DE_CHAO_ATIVA_OU_INVASORAS_50_DE_DOSSEL("Citrus, cobertura de chão ativa ou invasoras (50% de dossel)", 109),
	CITRUS_COBERTURA_DE_CHAO_ATIVA_OU_INVASORAS_20_DE_DOSSEL("Citrus, cobertura de chão ativa ou invasoras (20% de dossel)", 110),
	KIWI("Kiwi", 111),
	OLIVEIRA_40_A_60_DE_COBERTURA_DO_SOLO_PELO_DOSSEL("Oliveira (40 a 60% de cobertura do solo pelo dossel)", 112),
	PISTACHE_SEM_COBERTURA_DO_SOLO("Pistache, sem cobertura do solo", 113),
	NOGUEIRA_POMARES("Nogueira (pomares)", 114),
	CONIFERAS("Coníferas", 115),
	BANHADOS_COM_TABOAS_JUNCOS_COM_GEADAS("Banhados com taboas, juncos, com geadas", 116),
	BANHADOS_COM_TABOAS_JUNCOS_SEM_GEADAS("Banhados com taboas, juncos, sem geadas", 117),
	BANHADOS_VEGETACAO_BAIXA_SEM_GEADAS("Banhados, vegetação baixa, sem geadas", 118),
	PANTANO_BANHADOS_AGUA_ESTAGNADA("Pântano, banhados, água estagnada", 119),
	PANTANO_BANHADO_SOLO_UMIDO("Pântano, banhado, solo úmido", 120),
	CANA_DE_ACUCAR("Cana-de-açúcar", 121),
	TRIGO("Trigo", 130),
	ABIU("Abiu", 1004),
	ACAI("Açaí", 1005),
	ACEROLA("Acerola", 1006),
	AMEIXA("Ameixa", 1007),
	ARACA("Araça", 1008),
	ATEMOIA("Atemoia", 1009),
	BURITI("Buriti", 1013),
	BURITIBA("Buritiba", 1014),
	CAJU("Caju", 1015),
	CAQUI("Caqui", 1016),
	CARAMBOLA("Carambola", 1017),
	CAJA("Caja", 1018),
	CAJAMANGA("Cajamanga", 1019),
	COCO_VERDE("Coco Verde", 1020),
	CUPUACU("Cupuaçu", 1021),
	FIGO("Figo", 1022),
	GOIABA("Goiaba", 1023),
	GRAVIOLA("Graviola", 1024),
	JABOTICABA("Jaboticaba", 1025),
	JACA("Jaca", 1026),
	JAMBO("Jambo", 1027),
	JENIPAPO("Jenipapo", 1028),
	JUCARA("Juçara", 1029),
	LICHIA("Lichia", 1031),
	MANGABA("Mangaba", 1034),
	MANGOSTAO("Mangostao", 1035),
	MAMAO("Mamao", 1036),
	MANGA("Manga", 1037),
	MARACUJA("Maracuja", 1038),
	MURICI("Murici", 1039),
	NECTARINA("Nectarina", 1040),
	NOZ_MACADAMIA("Noz Macadamia", 1041),
	PEQUI("Pequi", 1042),
	PESSEGO("Pessego", 1043),
	PINHA("Pinha", 1044),
	PITANGA("Pitanga", 1045),
	PUPUNHA("Pupunha", 1046),
	RAMBUTAN("Rambutan", 1047),
	ROMA("Roma", 1048),
	SAPOTI("Sapoti", 1049),
	SERIGUELA("Seriguela", 1050),
	TAMARINDO("Tamarindo", 1051),
	TANGERINA("Tangerina", 1052),
	UMBU("Umbu", 1054),
	AIPIM("Aipim", 1062),
	BATATINHA("Batatinha", 1068),
	CANELA("Canela", 1071),
	CHUCHU("Chuchu", 1074),
	COENTRO("Coentro", 1075),
	COMINHO("Cominho", 1076),
	INHAME("Inhame", 1079),
	QUIABO("Quiabo", 1086),
	PIMENTA("Pimenta", 1090),
	MAXIXE("Maxixe", 1092),
	CARA("Cará", 1093),
	COUVE_OU_COUVE_SIMPLES("Couve (ou Couve simples)", 1094),
	FEIJAO_VIGNA("Feijão Vigna", 1099),
	ALGAROBA("Algaroba", 1103),
	FLORES("FLORES", 1105),
	CROTALARIA_ARBUSTO("Crotalaria (Arbusto)", 1108),
	CAJARANA("Cajarana", 1113),
	BUCHA("Bucha", 1115),
	VAGEM("Vagem", 1116),
	COGUMELO("Cogumelo", 1117),
	CEBOLINHA("Cebolinha", 1118),
	SALSA("Salsa", 1119),
	HORTALICAS("Hortaliças", 1120),
	COCO_SECO("Coco Seco", 1122),
	MILHO_VERDE("Milho-verde", 1123),
	GILO("Giló", 1126),
	FUMO("Fumo", 1127),
	POMAR("Pomar", 1129),
	EUCALIPITO("Eucalipito", 1130);


    private int chave;
    private String valor;

    TipoCultura(String valor, int chave) {
        this.valor = valor;
        this.chave = chave;
    }

	public int getChave() {
		return chave;
	}

	public void setChave(int chave) {
		this.chave = chave;
	}

	public String getValor() {
		return valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
